<?php

namespace SISAC\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use SISAC\Presenters\AlunoPresenter;
use SISAC\Repositories\AlunoRepository;
use SISAC\Entities\Aluno;
use SISAC\Validators\AlunoValidator;


/**
 * Class AlunoRepositoryEloquent
 * @package namespace SISAC\Repositories;
 */
class AlunoRepositoryEloquent extends BaseRepository implements AlunoRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Aluno::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {

        return AlunoValidator::class;
    }


    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function presenter()
    {
        return AlunoPresenter::class; // TODO: Change the autogenerated stub
    }
}
